name: Node CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
        npm-script:
          - test:js
          - test:types
          - verify
          - verify:git-clean
          - lint:js
          - lint:ts
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        env:
          CI: 'true'
        run: npm run ${{ matrix.npm-script }}
